### ISSUE TITLE
Issues with settings

### ISSUE THREAD

**Issue by mtran45** [nicojeske/mousewheel-image-zoom#34]
Step size

- Can't select 25

Initial Size

- Setting is not persisted

**Comment by Mideks** [comment]
I can't reproduce 1st bug. Moreover, you can change the value with the arrows.
https://github.com/nicojeske/mousewheel-image-zoom/assets/38502324/bb526deb-f077-4eea-9d37-0d5da5f701ac

About the second one, it seems to be a visual bug. Because the setting is saved to the settings file correctly after the change, and it also works correctly if the image has not been resized. Also, the setting is not actually reset when you go to the settings again. Just a visual bug...
