### ISSUE TITLE
Support for excalidraw images

### ISSUE THREAD

**Issue by icr1001** [nicojeske/mousewheel-image-zoom#6]
Thank your for this amazing plugin!!! 

Is it possible to add support for excalidraw images? They also use the format: 
 `[[image.excalidraw|100]], [[image.excalidraw|100x100]]`

Here is the excalidraw plugin for reference:
[zsviczian/obsidian-excalidraw-plugin](https://github.com/zsviczian/obsidian-excalidraw-plugin)

**Comment by nicojeske** [comment]
Hi there,

I just released a new update that should add support for excalidraw images.

But as I am not using excalidraw myself I only tested basic scenarios. So please also test this on your side and notify me, if you find any errors.

(You will likely see some flickering when resizing the images. This happens because excalidraw needs to redraw/regenerate the images after resizing.)

**Comment by nicojeske** [comment]
Feel free to reopen this issue if you still encounter any problems.

**Comment by icr1001** [comment]
Thank you very much!! it works perfectly
